[2025-01-27T18:36:28.060-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:36:15+00:00 [queued]>
[2025-01-27T18:36:28.063-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:36:15+00:00 [queued]>
[2025-01-27T18:36:28.063-0300] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-27T18:36:28.161-0300] {taskinstance.py:2191} INFO - Executing <Task(ExternalTaskSensor): wait_step_1> on 2025-01-27 21:36:15+00:00
[2025-01-27T18:36:28.164-0300] {standard_task_runner.py:60} INFO - Started process 175882 to run task
[2025-01-27T18:36:28.167-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'wait_step_1', 'manual__2025-01-27T21:36:15+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/step2.py', '--cfg-path', '/tmp/tmp8w5cqgfz']
[2025-01-27T18:36:28.168-0300] {standard_task_runner.py:88} INFO - Job 65: Subtask wait_step_1
[2025-01-27T18:36:28.267-0300] {task_command.py:423} INFO - Running <TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:36:15+00:00 [running]> on host victor-MS-7C52
[2025-01-27T18:36:28.506-0300] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data' AIRFLOW_CTX_TASK_ID='wait_step_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T21:36:15+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T21:36:15+00:00'
[2025-01-27T18:36:28.506-0300] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 240, in poke
    dttm_filter = self._get_dttm_filter(context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 229, in _get_dttm_filter
    dttm = self._handle_execution_date_fn(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 468, in _handle_execution_date_fn
    return kwargs_callable(logical_date, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 211, in kwargs_func
    kwargs = determine_kwargs(func, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 197, in determine_kwargs
    return KeywordParameters.determine(func, args, kwargs).unpacking()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/Desktop/TESTE/code-challenge/.meltano/utilities/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 163, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'context' in args is a part of kwargs and therefore reserved.
[2025-01-27T18:36:28.510-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_data, task_id=wait_step_1, execution_date=20250127T213615, start_date=20250127T213628, end_date=20250127T213628
[2025-01-27T18:36:28.610-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 65 for task wait_step_1 (The key 'context' in args is a part of kwargs and therefore reserved.; 175882)
[2025-01-27T18:36:28.619-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-27T18:36:28.633-0300] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
