[2025-01-27T19:02:53.089-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T22:02:42+00:00 [queued]>
[2025-01-27T19:02:53.092-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T22:02:42+00:00 [queued]>
[2025-01-27T19:02:53.092-0300] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-27T19:02:53.255-0300] {taskinstance.py:2191} INFO - Executing <Task(ExternalTaskSensor): wait_step_1> on 2025-01-27 22:02:42+00:00
[2025-01-27T19:02:53.259-0300] {standard_task_runner.py:60} INFO - Started process 184087 to run task
[2025-01-27T19:02:53.262-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'wait_step_1', 'manual__2025-01-27T22:02:42+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/step2.py', '--cfg-path', '/tmp/tmptyaa4pag']
[2025-01-27T19:02:53.263-0300] {standard_task_runner.py:88} INFO - Job 75: Subtask wait_step_1
[2025-01-27T19:02:53.414-0300] {task_command.py:423} INFO - Running <TaskInstance: load_data.wait_step_1 manual__2025-01-27T22:02:42+00:00 [running]> on host victor-MS-7C52
[2025-01-27T19:02:53.851-0300] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data' AIRFLOW_CTX_TASK_ID='wait_step_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T22:02:42+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T22:02:42+00:00'
[2025-01-27T19:02:53.852-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T22:02:42+00:00 ... 
[2025-01-27T19:03:53.854-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T22:02:42+00:00 ... 
[2025-01-27T19:04:53.856-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T22:02:42+00:00 ... 
[2025-01-27T19:05:53.858-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T22:02:42+00:00 ... 
[2025-01-27T19:06:24.075-0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-27T19:06:24.086-0300] {process_utils.py:131} INFO - Sending 15 to group 184087. PIDs of all processes in the group: [184087]
[2025-01-27T19:06:24.086-0300] {process_utils.py:86} INFO - Sending the signal 15 to group 184087
[2025-01-27T19:06:24.087-0300] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-27T19:06:24.178-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=184087, status='terminated', exitcode=0, started='19:02:52') (184087) terminated with exit code 0
