[2025-01-27T18:59:32.731-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:59:18+00:00 [queued]>
[2025-01-27T18:59:32.813-0300] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:59:18+00:00 [queued]>
[2025-01-27T18:59:32.814-0300] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-27T18:59:32.964-0300] {taskinstance.py:2191} INFO - Executing <Task(ExternalTaskSensor): wait_step_1> on 2025-01-27 21:59:18+00:00
[2025-01-27T18:59:32.968-0300] {standard_task_runner.py:60} INFO - Started process 181779 to run task
[2025-01-27T18:59:32.970-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'wait_step_1', 'manual__2025-01-27T21:59:18+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/step2.py', '--cfg-path', '/tmp/tmpu0z9rmda']
[2025-01-27T18:59:32.972-0300] {standard_task_runner.py:88} INFO - Job 70: Subtask wait_step_1
[2025-01-27T18:59:33.076-0300] {task_command.py:423} INFO - Running <TaskInstance: load_data.wait_step_1 manual__2025-01-27T21:59:18+00:00 [running]> on host victor-MS-7C52
[2025-01-27T18:59:33.289-0300] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data' AIRFLOW_CTX_TASK_ID='wait_step_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T21:59:18+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T21:59:18+00:00'
[2025-01-27T18:59:33.290-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T21:59:18+00:00 ... 
[2025-01-27T19:00:33.292-0300] {external_task.py:260} INFO - Poking for DAG 'extract_data' on 2025-01-27T21:59:18+00:00 ... 
[2025-01-27T19:00:50.348-0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-27T19:00:50.357-0300] {process_utils.py:131} INFO - Sending 15 to group 181779. PIDs of all processes in the group: [181779]
[2025-01-27T19:00:50.358-0300] {process_utils.py:86} INFO - Sending the signal 15 to group 181779
[2025-01-27T19:00:50.358-0300] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-27T19:00:50.490-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=181779, status='terminated', exitcode=0, started='18:59:32') (181779) terminated with exit code 0
